[[chapters]]
title = "UAM RL"
file = "main.typ"

[[chapters]]
title = "Introducción"
file = "introduccion.typ"

[[chapters]]
title = "Aproximación de función de valor"
file = "aprox_fvalor.typ"

[[chapters]]
title = "Métodos de gradiente de políticas"
file = "policy_gradient.typ"

[[chapters]]
title = "LoRA como aproximación de baja-rango"
file = "LoRA_baja-rango.typ"

[[chapters]]
title = "Notas"
file = "R1.typ"
